export const MILL_LIST_REQUEST = 'MILL_LIST_REQUEST';
export const MILL_LIST_SUCCESS = 'MILL_LIST_SUCCESS';
export const MILL_LIST_FAIL = 'MILL_LIST_FAIL';

export const MILL_DETAILS_REQUEST = 'MILL_DETAILS_REQUEST';
export const MILL_DETAILS_SUCCESS = 'MILL_DETAILS_SUCCESS';
export const MILL_DETAILS_FAIL = 'MILL_DETAILS_FAIL';

export const MILL_DELETE_REQUEST = 'MILL_DELETE_REQUEST';
export const MILL_DELETE_SUCCESS = 'MILL_DELETE_SUCCESS';
export const MILL_DELETE_FAIL = 'MILL_DELETE_FAIL';

export const MILL_CREATE_REQUEST = 'MILL_CREATE_REQUEST';
export const MILL_CREATE_SUCCESS = 'MILL_CREATE_SUCCESS';
export const MILL_CREATE_FAIL = 'MILL_CREATE_FAIL';
export const MILL_CREATE_RESET = 'MILL_CREATE_RESET';

export const MILL_UPDATE_REQUEST = 'MILL_UPDATE_REQUEST';
export const MILL_UPDATE_SUCCESS = 'MILL_UPDATE_SUCCESS';
export const MILL_UPDATE_FAIL = 'MILL_UPDATE_FAIL';
export const MILL_UPDATE_RESET = 'MILL_UPDATE_RESET';
