export const TROLLY_CREATE_REQUEST = 'TROLLY_CREATE_REQUEST';
export const TROLLY_CREATE_SUCCESS = 'TROLLY_CREATE_SUCCESS';
export const TROLLY_CREATE_FAIL = 'TROLLY_CREATE_FAIL';

export const TROLLY_CREATE_RESET = 'TROLLY_CREATE_RESET';

export const TROLLY_LIST_REQUEST = 'TROLLY_LIST_REQUEST';
export const TROLLY_LIST_SUCCESS = 'TROLLY_LIST_SUCCESS';
export const TROLLY_LIST_FAIL = 'TROLLY_LIST_FAIL';
export const TROLLY_LIST_RESET = 'TROLLY_LIST_RESET';

export const TROLLY_DELETE_REQUEST = 'TROLLY_DELETE_REQUEST';
export const TROLLY_DELETE_SUCCESS = 'TROLLY_DELETE_SUCCESS';
export const TROLLY_DELETE_FAIL = 'TROLLY_DELETE_FAIL';

export const TROLLY_UPDATE_REQUEST = 'TROLLY_UPDATE_REQUEST';
export const TROLLY_UPDATE_SUCCESS = 'TROLLY_UPDATE_SUCCESS';
export const TROLLY_UPDATE_FAIL = 'TROLLY_UPDATE_FAIL';
export const TROLLY_UPDATE_RESET = 'TROLLY_UPDATE_RESET';

export const TROLLY_DETAILS_REQUEST = 'TROLLY_DETAILS_REQUEST';
export const TROLLY_DETAILS_SUCCESS = 'TROLLY_DETAILS_SUCCESS';
export const TROLLY_DETAILS_FAIL = 'TROLLY_DETAILS_FAIL';
export const TROLLY_DETAILS_RESET = 'TROLLY_DETAILS_RESET';
