export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST';
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS';
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL';

export const VENDOR_DETAILS_REQUEST = 'VENDOR_DETAILS_REQUEST';
export const VENDOR_DETAILS_SUCCESS = 'VENDOR_DETAILS_SUCCESS';
export const VENDOR_DETAILS_FAIL = 'VENDOR_DETAILS_FAIL';

export const VENDOR_DELETE_REQUEST = 'VENDOR_DELETE_REQUEST';
export const VENDOR_DELETE_SUCCESS = 'VENDOR_DELETE_SUCCESS';
export const VENDOR_DELETE_FAIL = 'VENDOR_DELETE_FAIL';

export const VENDOR_APPROVE_REQUEST = 'VENDOR_APPROVE_REQUEST';
export const VENDOR_APPROVE_SUCCESS = 'VENDOR_APPROVE_SUCCESS';
export const VENDOR_APPROVE_FAIL = 'VENDOR_APPROVE_FAIL';

export const VENDOR_CREATE_REQUEST = 'VENDOR_CREATE_REQUEST';
export const VENDOR_CREATE_SUCCESS = 'VENDOR_CREATE_SUCCESS';
export const VENDOR_CREATE_FAIL = 'VENDOR_CREATE_FAIL';
export const VENDOR_CREATE_RESET = 'VENDOR_CREATE_RESET';

export const VENDOR_UPDATE_REQUEST = 'VENDOR_UPDATE_REQUEST';
export const VENDOR_UPDATE_SUCCESS = 'VENDOR_UPDATE_SUCCESS';
export const VENDOR_UPDATE_FAIL = 'VENDOR_UPDATE_FAIL';
export const VENDOR_UPDATE_RESET = 'VENDOR_UPDATE_RESET';
