export const VENUE_CREATE_REQUEST = 'VENUE_CREATE_REQUEST';
export const VENUE_CREATE_SUCCESS = 'VENUE_CREATE_SUCCESS';
export const VENUE_CREATE_FAIL = 'VENUE_CREATE_FAIL';

export const VENUE_CREATE_RESET = 'VENUE_CREATE_RESET';

export const VENUE_LIST_REQUEST = 'VENUE_LIST_REQUEST';
export const VENUE_LIST_SUCCESS = 'VENUE_LIST_SUCCESS';
export const VENUE_LIST_FAIL = 'VENUE_LIST_FAIL';
export const VENUE_LIST_RESET = 'VENUE_LIST_RESET';

export const VENUE_DELETE_REQUEST = 'VENUE_DELETE_REQUEST';
export const VENUE_DELETE_SUCCESS = 'VENUE_DELETE_SUCCESS';
export const VENUE_DELETE_FAIL = 'VENUE_DELETE_FAIL';

export const VENUE_UPDATE_REQUEST = 'VENUE_UPDATE_REQUEST';
export const VENUE_UPDATE_SUCCESS = 'VENUE_UPDATE_SUCCESS';
export const VENUE_UPDATE_FAIL = 'VENUE_UPDATE_FAIL';
export const VENUE_UPDATE_RESET = 'VENUE_UPDATE_RESET';

export const VENUE_DETAILS_REQUEST = 'VENUE_DETAILS_REQUEST';
export const VENUE_DETAILS_SUCCESS = 'VENUE_DETAILS_SUCCESS';
export const VENUE_DETAILS_FAIL = 'VENUE_DETAILS_FAIL';
export const VENUE_DETAILS_RESET = 'VENUE_DETAILS_RESET';
